# Generated by Django 3.2.8 on 2021-12-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0007_remove_votes_votecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_vote', to='Forum.post'),
            preserve_default=False,
        ),
    ]
