# Generated by Django 3.2.8 on 2021-12-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0008_votes_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='post',
        ),
    ]
