# Generated by Django 3.2.8 on 2021-12-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0013_postreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postreport',
        ),
    ]
