# Generated by Django 4.0 on 2022-01-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Forum', '0023_subcommentvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcommentreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('report_message', models.TextField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('subcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomment', to='Forum.subcomment')),
            ],
        ),
    ]
